//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LIVEX
{
    using System;
    using System.Collections.Generic;
    
    public partial class alumno_factura
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public alumno_factura()
        {
            this.alumno = new HashSet<alumno>();
        }
    
        public int idalumno_factura { get; set; }
        public string nombre { get; set; }
        public string rfc { get; set; }
        public string estado { get; set; }
        public string ciudad { get; set; }
        public string direccion { get; set; }
        public string direccion_no { get; set; }
        public string colonia { get; set; }
        public string cp { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<alumno> alumno { get; set; }
    }
}
