//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LIVEX
{
    using System;
    using System.Collections.Generic;
    
    public partial class alumno
    {
        public int idalumno { get; set; }
        public string alumno_nombre { get; set; }
        public string alumno_apellido_p { get; set; }
        public string alumno_apellido_m { get; set; }
        public string fecha_nac { get; set; }
        public string telefono_casa { get; set; }
        public string telefono_celular { get; set; }
        public string domicilio_calle { get; set; }
        public string domicilio_no { get; set; }
        public string domicilio_col { get; set; }
        public string domicilio_mun { get; set; }
        public string domicilio_cp { get; set; }
        public string domicilio_edo { get; set; }
        public string curso_inicial { get; set; }
        public Nullable<int> grupo_id { get; set; }
        public Nullable<int> categoria_id { get; set; }
        public Nullable<int> facturacion_id { get; set; }
        public string picture { get; set; }
    
        public virtual alumno_factura alumno_factura { get; set; }
        public virtual grupo grupo { get; set; }
    }
}
