//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LIVEX
{
    using System;
    using System.Collections.Generic;
    
    public partial class asistencia_maestros
    {
        public Nullable<int> No { get; set; }
        public Nullable<int> DN { get; set; }
        public string UID { get; set; }
        public string Name { get; set; }
        public string Status { get; set; }
        public Nullable<int> Action { get; set; }
        public Nullable<int> APB { get; set; }
        public Nullable<int> JobCode { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public int asistencia_maestrosID { get; set; }
        public string filename { get; set; }
        public Nullable<int> hour { get; set; }
        public Nullable<int> min { get; set; }
        public Nullable<int> sec { get; set; }
    }
}
