//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LIVEX
{
    using System;
    using System.Collections.Generic;
    
    public partial class categoria
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public categoria()
        {
            this.grupo_categoria = new HashSet<grupo_categoria>();
        }
    
        public int idcategoria { get; set; }
        public string categoria_nombre { get; set; }
        public Nullable<decimal> precio { get; set; }
        public string tipo_periodo { get; set; }
        public string clasificacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<grupo_categoria> grupo_categoria { get; set; }
    }
}
