//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LIVEX
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class livexEntities : DbContext
    {
        public livexEntities()
            : base("name=livexEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<language> language { get; set; }
        public virtual DbSet<skills> skills { get; set; }
        public virtual DbSet<teacher_skills> teacher_skills { get; set; }
        public virtual DbSet<user> user { get; set; }
        public virtual DbSet<categoria> categoria { get; set; }
        public virtual DbSet<grupo_categoria> grupo_categoria { get; set; }
        public virtual DbSet<ciclo> ciclo { get; set; }
        public virtual DbSet<grupo> grupo { get; set; }
        public virtual DbSet<alumno_factura> alumno_factura { get; set; }
        public virtual DbSet<alumno> alumno { get; set; }
        public virtual DbSet<teacher> teacher { get; set; }
        public virtual DbSet<asistencia_maestros> asistencia_maestros { get; set; }
    }
}
