//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LIVEX
{
    using System;
    using System.Collections.Generic;
    
    public partial class teacher_skills
    {
        public int idteacher_skills { get; set; }
        public int teacherID { get; set; }
        public int skillID { get; set; }
    
        public virtual teacher teacher { get; set; }
    }
}
